version: "3.9"
services:
  back_end:
    restart: always
    container_name: "back_end"
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
      - full_stack_network
      - network_with_redis
    ports:
      - "8080:8080"

  redis_cache:
    restart: always
    container_name: "redis_cache"
    image: redis:latest
    networks:
      - network_with_redis
    ports:
      - "6379:6379"

networks:
  full_stack_network:
    driver: bridge

  network_with_redis:
    driver: bridge