name: GoTest
on:
  push:
    branches: ["develop", "master"]
  pull_request:
    branches: [ "develop", "master"]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Go build
        run: go build -v ./...

      - name: Go testing
        run: go test -v ./...

      - name: Golint install
        run: go install golang.org/x/lint/golint@latest

      - name: golint run
        run: golint ./...